development:
  adapter: postgresql
  database: rirc_development
  host: localhost

test:
  adapter: postgresql
  database: rirc_testing
  host: localhost

production:
  adapter: postgresql
  database: dc6c74ljfjl07u
  host: ec2-54-243-190-113.compute-1.amazonaws.com
  port: 5432
  user: bgogsrpcqtxigl
